server:
  port: 8989
  address: 0.0.0.0

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  application:
    name: AUTHORIZATION-SERVER
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/ecnam-auth-db?createDatabaseIfNotExist=true
    username: root
    password:
  sql:
    init:
      mode: never
  mail:
    host: smtp.mailtrap.io
    port: 25
    username: 184836e2d86b03
    password: 0dd87babe95622


eureka:
  client:
    serviceUrl:
      defaultZone:
        http://localhost:8761/eureka
    registerWithEureka:
      true
    fetchRegistry:
      true

security:
  oauth2:
    resource:
      filter-order: 3
  signing-key: <signing-key>

queue:
  name: myQueue